name: Clojure Lint

on:
  push:
    paths:
      - '**/*.clj'
      - '**/*.cljs'
      - '**/*.cljc'
      - '**/*.edn'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@12.1
        with:
          cli: latest

      - name: Install clj-kondo
        uses: DeLaGuardo/setup-clj-kondo@master
        with:
          version: '2023.10.20'

      - name: Run clj-kondo
        run: |
          # Find all directories containing Clojure files and lint them
          for dir in $(find . -type f -name "*.clj" -o -name "*.cljs" -o -name "*.cljc" | xargs -I {} dirname {} | sort -u); do
            echo "Linting directory: $dir"
            clj-kondo --lint "$dir"
          done